baseURL = 'https://attadeurtia.github.io/blog/'
languageCode = 'FR-fr'
DefaultContentLanguage = "fr"
title = 'Geoffrey'
theme = "cactus"

[params]
  description = "Idée en vrac, des fois tech, des fois expérience, des fois explication, au-delà de partager mes découvertes, ça me permet aussi de m’en souvenir."
  showAllPostsOnHomePage = true
  postsOnHomePage = 5 # this option will be ignored

  tagsOverview = true

  colortheme = "white" # dark, light, white, or classic
  css = ["css/custom.css"]

  mathjax = true  # not required




# table des matières
  tocInline = true

  showProjectsList = true
  projectsUrl = "https://attadeurtia.github.io/blog/"

  rss = true

    mainSection = "posts"

  mainSectionTitle = "Articles"


[[params.social]]
  name = "github"
  link = "https://github.com/Attadeurtia"

[[params.social]]
  name = "email"
  link = "geoffreypose@gmail.com" # no need for "mailto:" at the start

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/geoffrey-pos%C3%A9-299709200/"


[menu]

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Tout les articles"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "À propos"
url = "/about"
weight = 4

[about]
  avatar = "img/avatar.jpg"
  name = "Geoffrey Posé"
  bio = "Développeur web, passionné par la programmation, l'expérience utilisateur et la sécurité informatique."
  location = "France"
  email = ""
