baseURL = 'https://attadeurtia.github.io/'
languageCode = 'en-us'
title = 'Geoffrey 3'
theme = 'ananke'

[module]
  [[module.imports]]
    path = 'github.com/hugomods/umami-analytics'

[params]
  [params.services]
    [params.services.umami_analytics]
      id = '8261e837-91d2-433d-ba96-be0441457e4a'
      script_url = 'https://cloud.umami.is/script.js'
